### ISSUE TITLE
カレントユーザーのレコードをUserのクラス変数としてセットしてしまっている

### ISSUE THREAD

**Issue by asip** [shiramizu-junya/personal_history#55]
バグを発見したので、issue として報告させていただきます。

https://github.com/shiramizu-junya/personal_history/blob/77d2de9b37c95a5644344a743b8c97a806870316/app/controllers/application_controller.rb#L15
https://github.com/shiramizu-junya/personal_history/blob/77d2de9b37c95a5644344a743b8c97a806870316/app/validators/event_age_validator.rb#L6

Unicornのようなリクエストに対してプロセスを割り当てるマルチプロセスのAPサーバ上で動かす場合、
プロセス間でメモリを共有しないので、このバグは表面化しないハズですが、
Pumaのようなリクエストに対してスレッドを割り当てるマルチスレッド(厳密には、マルチプロセス&
マルチスレッド)のAPサーバの場合、スレッド間で、メモリを共有しているので、
User.current_user のように、クラス変数に値をセットしていると、APIサーバ上の同一プロセス上で
動作している(リクエストを処理している)全てのスレッドから呼び出しているコントローラetcから、
このクラス変数にアクセスし、値の書き換えを行うことが可能、なので、
具体的には、このクラス変数にリクエストAでカレントユーザーをセットした後、リクエストBにより
このクラス変数が上書きされ、リクエストAでこのクラス変数を参照した際、リクエストB
のカレントユーザーを参照してしまっている、ということが起こりえます。

カレントユーザーのレコードを 引き回したいので あれば、Userのクラス変数にセットする、
のではなく、スレッドローカルな変数を作成し、そちらにセットする、ようにすることを
オススメします。

下記ページに書かれている どちらかの方法で、スレッドローカルな変数を作成すればよいハズです。

[RubyのThread#[]=メソッドの注意点](https://qiita.com/Eustace/items/5e99d453f798641da047)
[`Thread.current[:hoge]`はスレッドローカル変数を参照していると思いきや
実際はファイバーローカル変数だった](https://blog.willnet.in/entry/2021/12/23/184123)

**Comment by shiramizu-junya** [comment]
> スレッドローカルな変数を作成し、そちらにセットする、ようにすることをオススメします。

学習不足で申し訳ありません。
メモリを意識してコードを組むことを学ばせていただきました。
記事を拝見し、修正をしたいと思います🙏

**Comment by asip** [comment]
@shiramizu-junya

実務未経験の方が知らないことが多々あるのは、当たり前なので、謝る？必要はないです。
知らないことは、これから、知っていけばいいので。

Railsに限らず、他の言語や他のフレームワークでも、スレッドセーフなプログラミングを
求められる(意識しておかなくはならない)ことは結構あるので、心に留めておかれることを
オススメします。

↑では、スレッドローカルな変数を作成しての参照をオススメしましたが、このリポジトリのコードを
再度チラ見した限りでは、Validator内で参照しているだけ なこともあり、カレントユーザをスレッド
ローカルな変数として保持する必要はないように思えます。

参照しているバリデータは、Eventモデルで利用するバリデータとして実装されているので、
バリデータ内で record.my_history.user(バリデータを呼び出しているEventモデルの
インスタンスがカレントユーザーのイベントの場合) で参照すれば事足りるハズです。

スレッドセーフな変数として、作成してしまうと、Grep等で、検索しないと、
その変数が、どこで作成され、利用されているか、わからず、
また、オブジェクト志向のカプセル化を崩してしまう？ので、
スレッドセーフな変数を作成する際には、その変数をスレッドセーフな変数と
して作成する必要が本当にあるかを、十分検討してから、必要であれば
作成されることをオススメします。

ご参考まで。

**Comment by shiramizu-junya** [comment]
05abd7c で修正しました。
